UPDATE redirects
SET http_status_code =
        CASE http_status_code
            WHEN 'MOVED_PERMANENTLY' THEN 'HTTP_301_MOVED_PERMANENTLY'
            WHEN 'FOUND' THEN 'HTTP_302_FOUND'
            WHEN 'TEMPORARY_REDIRECT' THEN 'HTTP_307_TEMPORARY_REDIRECT'
            WHEN 'PERMANENT_REDIRECT' THEN 'HTTP_308_PERMANENT_REDIRECT'
            END;