<!DOCTYPE html>
<html lang="en">
    @template.fragments.header()

    <body>
        @template.fragments.nav()
        <main class="container" style="padding-top: 1.5em;">
            <div style="text-align: center;">
                <h1>
                    re:Director
                </h1>
                <h6>
                    Manage Redirects Like a Pro
                </h6>
                <p>
                    <small>
                        Connect any domain and set up custom redirects in seconds. <br />
                        re:Director gives you full control over your domain traffic. <br />
                        Set up smart, reliable redirects with minimal setup. <br />
                        Perfect for marketing, rebranding, or managing multiple sites from one place.
                    </small>
                </p>
                <a href="/redirects">
                    <button>
                        Get Started
                    </button>
                </a>
            </div>
        </main>
        @template.fragments.footer()
        @template.fragments.js()
    </body>
</html>