<header class="container">
    <nav>
        <ul>
            <li>
                <a href="/">
                    <img src="/img/re-director.svg" alt="Logo" style="width: 2.2em"/>
                </a>
            </li>
            <li style="margin-right: 1em">
                <a href="/">
                    <h1>re:Director</h1>
                </a>
            </li>
            <li>
                <a href="/redirects">
                    Redirects
                </a>
            </li>
        </ul>
        <ul>
            <!--
            <li>
                <button>Login</button>
            </li>
            <li>
                <button>Logout</button>
            </li>
            -->
        </ul>
    </nav>
    <hr>
</header>